spring:
  data:
    mongodb:
      uri: mongodb+srv://eshopdb:eshopdb@cluster0.ws1zrdj.mongodb.net/eshop-db?retryWrites=true&w=majority&appName=Cluster0

#Actuator Prometheus config
management:
  endpoints:
    web:
      exposure:
        include: prometheus
