#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/  # URL of the Eureka server

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/eshop-db

#Actuator Prometheus config
management:
  endpoints:
    web:
      exposure:
        include: *
